### ISSUE TITLE
libticables build failing

### ISSUE THREAD

**Issue by catastropher** [debrouxl/tilibs#23]
When trying to build libticables from the master branch I get this error:
```
make[2]: Entering directory '/home/michael/code/tilibs/libticables/trunk/po'
test ! -f ./libticables2.pot || \
  test -z "fr.gmo" || make fr.gmo
make[3]: Entering directory '/home/michael/code/tilibs/libticables/trunk/po'
: --update  --lang=fr fr.po libticables2.pot
rm -f fr.gmo && : -c --statistics --verbose -o fr.gmo fr.po
mv: cannot stat 't-fr.gmo': No such file or directory
Makefile:154: recipe for target 'fr.gmo' failed
```
Do you have any idea what may be causing it? Thanks!

**Comment by debrouxl** [comment]
Hi Michael :)

I can't reproduce the issue in a fresh Debian 9 (Stretch) container. The 4 libti*, gfm and tilp built successfully.
In the output you've posted, ": --update <...>" and ": -c <...>" look odd. Did you successfully install all of the build dependencies listed for multiple distro families in the install script, one of the shortlinks for which is https://ti-pla.net/tilpinst ?

**Comment by catastropher** [comment]
Hi Lionel!

Thank you so much, I was indeed missing some of the dependencies. I didn't even realize that that script existed; I was just trying to build the libraries based off the instructions in the individual readme's. Thanks again!
