### ISSUE TITLE
./linux/link_usb.c:94:11: fatal error: 'usb.h' file not found

### ISSUE THREAD

**Issue by mrabrams** [debrouxl/tilibs#39]
When trying to compile on Mac, I keep on getting this issue:

`./linux/link_usb.c:94:11: fatal error: 'usb.h' file not found`

I've tried relocating the existing `usb.h` file in the win32 to the correct route to no avail.

Any clues?

**Comment by debrouxl** [comment]
You need the libusb 1.x development files.
The install script from the debrouxl/tilp_and_gfm repo, for which a shortlink is https://ti-pla.net/tilpinst , is known to work on MacOS X, provided the build dependencies listed by that script when it starts are installed.
