### ISSUE TITLE
Nspire dirlist broken when folder names contain dots

### ISSUE THREAD

**Issue by PuyGonzalo** [debrouxl/tilibs#52]
Hello! I've install TiLP succesfully in my laptop (Thinkpad T480), but I keep getting the error: "Msg: the variable or directory does not exist." when I try to list calculator content.

This is the full output: [https://pastebin.com/tUpXcN1Z](url)

Edit: I have a TI-nspire CX CAS

**Comment by debrouxl** [comment]
This issue has been reported again today by Adriweb. Last time, I failed to comprehend what was going on, but I think I found something.

**Comment by PuyGonzalo** [comment]
Hello, is there any updates on this ? I'm still having this issue and was never able to use TiLP properly.

**Comment by PuyGonzalo** [comment]
Well... I've tried deleting the folder which name contain a dot and now I can use TiLP. I consider this issue closed
